name: CI

on:
  push:
    paths-ignore:
      - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: curl -v https://www.golem.de/
