name: Block PR by Label

on:
  pull_request:
    types: [ labeled, unlabeled ]

jobs:
  check-label:
    runs-on: ubuntu-20.04
    steps:
      - name: check label
        run: |
          ! jq -e '.pull_request.labels[] | select( .name == "do not merge yet")' "$GITHUB_EVENT_PATH"
